# Generated by Django 5.1.6 on 2025-02-07 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='date_time',
            field=models.DateField(auto_now_add=True, verbose_name='date time'),
        ),
    ]
